name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare for installations
      run: sudo apt update -y
    - name: Install Python
      run: sudo apt install -y python3-pip python3-dev python3-venv
    - name: Install ghostscript & imagemagick
      run: sudo apt install -y ghostscript libmagickwand-dev
    - name: Remove policy.xml
      run: sudo rm /etc/ImageMagick-6/policy.xml
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Configure pip caching
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt')}}-${{ hashFiles('**/requirements-dev.txt') }}
    - name: Install Python dependencies
      run: make venv
    - name: Validate against psf/black
      run: make check-black
    - name: Validate against flake8
      run: make check-flake
    - name: Run tests
      run: make tests
    - name: Upload code coverage
      uses: codecov/codecov-action@v1.0.12
