name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install ghostscript libmagickwand-dev
      run: sudo apt-get install libxml2-utils
    - name: Remove policy.xml
      run: sudo rm /etc/ImageMagick-6/policy.xml
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt')}}-${{ hashFiles('**/requirements-dev.txt') }}
    - name: Install Python dependencies
      run: make venv
    - name: Validate against psf/black
      run: make check-black
    - name: Validate against flake8
      run: make check-flake
    - name: Run tests
      run: make tests
    - name: Examine code coverage
      uses: codecov/codecov-action@v1.0.12
